### ISSUE TITLE
Should the core contributors also show up in the additional contributors list below?

### ISSUE THREAD

**Issue by lynnandtonic** [AmpersandJS/ampersandjs.com#24] opened 2014-06-24 16:18 UTC
Just curious if that seems weird.

**Comment by HenrikJoreteg** [comment] 2014-06-24 16:35
I had them removed at first, then yesterday Baldwin jokingly asked me if I had pushed any code to the project since I wasn't listed... lol. And it now says that it lists people by number of contributions... so i'm not quite sure what to do with all that.

**Comment by HenrikJoreteg** [comment] 2014-06-24 16:35
feedback appreciated.

**Comment by lynnandtonic** [comment] 2014-06-24 16:40
It seems weird to me.

I think it should either go back to excluding the core contributors and maybe edit the copy so it makes sense that the core contributors aren't in the list.

Or we could leave it as is and eliminate the core contributors part.

**Comment by HenrikJoreteg** [comment] 2014-06-24 16:43
I agree its weird, let's just go back to how it was. part of the issue is I want to include lance, because he's provided a ton of awesome feedback and I'd be happy to have him contribute to the project at any point but he hasn't directly committed any code.

**Comment by HenrikJoreteg** [comment] 2014-06-24 19:12
removed

**Closed as completed by HenrikJoreteg** 2014-06-24 19:12 UTC
